services:
- type: web
  name: mandee-wordpress
  env: docker
  plan: starter
  autoDeploy: true
  disk:
    name: mandee-wordpress
    mountPath: /var/www/html
    sizeGB: 20
  envVars:
  - fromGroup: code2pixels-main-env
