# services:
# # Production Services
# - type: web
#   name: detroit-axle-web-production
#   env: docker
#   region: ohio
#   plan: starter
#   branch: main
#   dockerfilePath: ./docker/Dockerfile.web
#   dockerContext: .
#   envVars:
#     - key: PHP_FPM_HOST
#       fromService:
#         name: detroit-axle-php-fpm-production
#         type: pserv
#         property: host
#     - key: PHP_FPM_PORT
#       fromService:
#         name: detroit-axle-php-fpm-production
#         type: pserv
#         property: port
#     - key: PHP_FPM_WP_ADMIN_HOST
#       fromService:
#         name: detroit-axle-php-fpm-admin-production
#         type: pserv
#         property: host
#     - key: PHP_FPM_WP_ADMIN_PORT
#       fromService:
#         name: detroit-axle-php-fpm-admin-production
#         type: pserv
#         property: port
#     - fromGroup: detroit-axle-env-var-group

# - type: web
#   name: detroit-axle-adminer-web-ohio
#   env: docker
#   region: ohio
#   plan: free
#   branch: main
#   dockerfilePath: ./docker/adminer/Dockerfile
#   dockerContext: .
#   autoDeploy: false

# envVarGroups:
# - name: code2pixels-env-var-group
#   envVars:
#     - key: AUTH_KEY
#       generateValue: true
#     - key: SECURE_AUTH_KEY
#       generateValue: true
#     - key: LOGGED_IN_KEY
#       generateValue: true
#     - key: NONCE_KEY
#       generateValue: true
#     - key: AUTH_SALT
#       generateValue: true
#     - key: SECURE_AUTH_SALT
#       generateValue: true
#     - key: LOGGED_IN_SALT
#       generateValue: true
#     - key: NONCE_SALT
#       generateValue: true