services:
- type: web
  name: mandee-wordpress
  env: docker
  plan: starter
  autoDeploy: false
  disk:
    name: mandee-wordpress
    mountPath: /var/www/html
    sizeGB: 20
  envVars:
  - key: WORDPRESS_DB_HOST
    value: code2pixels-mysql-database
  - key: WORDPRESS_DB_NAME
    fromService:
      name: code2pixels-mysql-database
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: WORDPRESS_DB_USER
    fromService:
      name:code2pixels-mysql-database
      type: pserv
      envVarKey: MYSQL_USER
  - key: WORDPRESS_DB_PASSWORD
    fromService:
      name: code2pixels-mysql-database
      type: pserv
      envVarKey: MYSQL_PASSWORD
